name: OTA_Client_Builder


on:
  pull_request:
  push:
    branches:
    - main

jobs:
  Ubuntu:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check_out code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version:"3.10.8"
      
      - name: Install Linux dependancies
        run : |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
        
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build OTA_client
        run: cd OTA_client && platformio run

        
