name: server_builder

on:
  pull_request:
  push:
    branches:
    - main
    - build_test

jobs:
  Ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v3
      with: 
        go-version: 1.19.x
    
    - name: Find_file
      run: cd OTA_server && ls -al
    
    - name: Build
      run: go build -v ./..
    
    - name: Create_release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: OTA_server/OTA_server.bin
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true


      
